import type { Employee, VacationRequest, LiveEmployee, WorkSession } from "./types";

export const CURRENT_USER: Employee = {
  id: "emp-001",
  name: "Alejandro",
  lastName: "Millán",
  email: "alejandro.millan@empresa.com",
  role: "Desarrollador Senior",
  department: "Tecnología",
  avatar: "",
  weeklyHours: 40,
  isAdmin: false,
  joinDate: "2022-03-15",
  phone: "+34 612 345 678",
  vacationDays: 23,
  vacationUsed: 8,
};

export const ADMIN_USER: Employee = {
  id: "admin-001",
  name: "María",
  lastName: "García",
  email: "maria.garcia@empresa.com",
  role: "Directora de RRHH",
  department: "Recursos Humanos",
  avatar: "",
  weeklyHours: 40,
  isAdmin: true,
  joinDate: "2020-01-10",
  phone: "+34 698 765 432",
  vacationDays: 23,
  vacationUsed: 5,
};

export const ALL_EMPLOYEES: Employee[] = [
  {
    id: "emp-001",
    name: "Alejandro",
    lastName: "Millán",
    email: "alejandro.millan@empresa.com",
    role: "Desarrollador Senior",
    department: "Tecnología",
    avatar: "",
    weeklyHours: 40,
    isAdmin: false,
    joinDate: "2022-03-15",
    vacationDays: 23,
    vacationUsed: 8,
  },
  {
    id: "emp-002",
    name: "Lucía",
    lastName: "Fernández",
    email: "lucia.fernandez@empresa.com",
    role: "Diseñadora UX",
    department: "Diseño",
    avatar: "",
    weeklyHours: 40,
    isAdmin: false,
    joinDate: "2021-06-01",
    vacationDays: 23,
    vacationUsed: 12,
  },
  {
    id: "emp-003",
    name: "Carlos",
    lastName: "Ruiz",
    email: "carlos.ruiz@empresa.com",
    role: "Project Manager",
    department: "Operaciones",
    avatar: "",
    weeklyHours: 40,
    isAdmin: false,
    joinDate: "2019-11-20",
    vacationDays: 25,
    vacationUsed: 10,
  },
  {
    id: "emp-004",
    name: "Ana",
    lastName: "Martínez",
    email: "ana.martinez@empresa.com",
    role: "Contable",
    department: "Finanzas",
    avatar: "",
    weeklyHours: 35,
    isAdmin: false,
    joinDate: "2023-01-09",
    vacationDays: 23,
    vacationUsed: 3,
  },
  {
    id: "emp-005",
    name: "David",
    lastName: "López",
    email: "david.lopez@empresa.com",
    role: "Comercial",
    department: "Ventas",
    avatar: "",
    weeklyHours: 40,
    isAdmin: false,
    joinDate: "2020-09-14",
    vacationDays: 23,
    vacationUsed: 15,
  },
  {
    id: "emp-006",
    name: "Sara",
    lastName: "Sánchez",
    email: "sara.sanchez@empresa.com",
    role: "Marketing Digital",
    department: "Marketing",
    avatar: "",
    weeklyHours: 40,
    isAdmin: false,
    joinDate: "2022-08-01",
    vacationDays: 23,
    vacationUsed: 6,
  },
  {
    id: "admin-001",
    name: "María",
    lastName: "García",
    email: "maria.garcia@empresa.com",
    role: "Directora RRHH",
    department: "RRHH",
    avatar: "",
    weeklyHours: 40,
    isAdmin: true,
    joinDate: "2020-01-10",
    vacationDays: 23,
    vacationUsed: 5,
  },
];

export const LIVE_EMPLOYEES: LiveEmployee[] = [
  { id: "emp-001", name: "Alejandro Millán", avatar: "", status: "working", entryTime: "08:45", elapsedMinutes: 215, department: "Tecnología" },
  { id: "emp-002", name: "Lucía Fernández", avatar: "", status: "working", entryTime: "09:00", elapsedMinutes: 200, department: "Diseño" },
  { id: "emp-003", name: "Carlos Ruiz", avatar: "", status: "paused", entryTime: "08:30", elapsedMinutes: 230, department: "Operaciones" },
  { id: "emp-005", name: "David López", avatar: "", status: "working", entryTime: "09:15", elapsedMinutes: 185, department: "Ventas" },
  { id: "emp-006", name: "Sara Sánchez", avatar: "", status: "working", entryTime: "08:00", elapsedMinutes: 260, department: "Marketing" },
  { id: "emp-004", name: "Ana Martínez", avatar: "", status: "absent", department: "Finanzas" },
];

export const VACATION_REQUESTS: VacationRequest[] = [
  {
    id: "req-001",
    employeeId: "emp-001",
    employeeName: "Alejandro Millán",
    type: "vacaciones",
    startDate: "2025-08-04",
    endDate: "2025-08-15",
    days: 10,
    status: "aprobada",
    notes: "Vacaciones de verano",
    createdAt: "2025-05-15T10:00:00",
    reviewedAt: "2025-05-16T09:00:00",
    reviewedBy: "admin-001",
  },
  {
    id: "req-002",
    employeeId: "emp-001",
    employeeName: "Alejandro Millán",
    type: "permiso",
    startDate: "2025-06-20",
    endDate: "2025-06-20",
    days: 1,
    status: "pendiente",
    notes: "Cita médica por la tarde",
    createdAt: "2025-06-10T08:30:00",
  },
  {
    id: "req-003",
    employeeId: "emp-002",
    employeeName: "Lucía Fernández",
    type: "vacaciones",
    startDate: "2025-07-07",
    endDate: "2025-07-18",
    days: 10,
    status: "pendiente",
    notes: "Vacaciones verano",
    createdAt: "2025-05-20T11:00:00",
  },
  {
    id: "req-004",
    employeeId: "emp-003",
    employeeName: "Carlos Ruiz",
    type: "baja_medica",
    startDate: "2025-05-28",
    endDate: "2025-06-02",
    days: 4,
    status: "aprobada",
    notes: "Baja por gripe",
    createdAt: "2025-05-28T07:00:00",
    reviewedAt: "2025-05-28T08:00:00",
    reviewedBy: "admin-001",
  },
  {
    id: "req-005",
    employeeId: "emp-005",
    employeeName: "David López",
    type: "ausencia_horas",
    startDate: "2025-06-12",
    endDate: "2025-06-12",
    days: 0.5,
    status: "rechazada",
    notes: "Gestión banco 2h",
    createdAt: "2025-06-09T09:00:00",
    reviewedAt: "2025-06-10T10:00:00",
    reviewedBy: "admin-001",
  },
];

export const WEEK_CHART_DATA = [
  { day: "Lun", hours: 8.2, target: 8 },
  { day: "Mar", hours: 7.8, target: 8 },
  { day: "Mié", hours: 9.1, target: 8 },
  { day: "Jue", hours: 8.5, target: 8 },
  { day: "Vie", hours: 6.5, target: 8 },
  { day: "Sáb", hours: 0, target: 0 },
  { day: "Dom", hours: 0, target: 0 },
];

export const RECENT_SESSIONS: WorkSession[] = [
  {
    id: "sess-001",
    employeeId: "emp-001",
    date: "2025-05-12",
    entryTime: "08:45",
    exitTime: "17:30",
    breaks: [{ start: "13:00", end: "14:00" }],
    totalMinutes: 465,
    status: "completed",
  },
  {
    id: "sess-002",
    employeeId: "emp-001",
    date: "2025-05-11",
    entryTime: "09:00",
    exitTime: "17:45",
    breaks: [{ start: "13:00", end: "14:00" }],
    totalMinutes: 465,
    status: "completed",
  },
  {
    id: "sess-003",
    employeeId: "emp-001",
    date: "2025-05-10",
    entryTime: "08:30",
    exitTime: "18:00",
    breaks: [{ start: "14:00", end: "15:00" }],
    totalMinutes: 510,
    status: "completed",
  },
];

export const MONTH_STATS = {
  month: "Mayo 2025",
  totalHours: 156.5,
  targetHours: 168,
  daysWorked: 18,
  workingDays: 21,
  overtimeHours: 4.5,
};
